server:
  port: 8888

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ygh_admin?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: YangHikariPool

  # redis配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 20
        # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-wulanchabu.aliyuncs.com
      keyid: LTAI5tPgN29EEJFwiqZsjiJN
      keysecret: TupU26hcFkHEr1bAfL91mX6xG5IkmJ
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: edu-ygh

